matrix:
  allow_failures:
    - env: CABALVER=head GHCVER=head

env:
 - CABALVER=1.22 GHCVER=7.10.3
 - CABALVER=1.24 GHCVER=8.0.1
 - CABALVER=head GHCVER=head

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER libicu-dev
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - cabal update
 - travis_retry cabal install --only-dependencies --enable-tests --enable-benchmarks

install:
 - cabal install -j1 --enable-tests --enable-benchmarks

script:
 - cabal test

notifications:
  irc: "chat.freenode.net#yi"
